DROP TABLE IF EXISTS MUTUAL_FUNDS;
CREATE TABLE MUTUAL_FUNDS(

AMC VARCHAR(100),
Fund_Name VARCHAR(100),
Morning_star_rating INT,
Value_Research_rating INT,
one_month_return REAL,
NAV REAL,
one_Year_return REAL,
three_Year_Return REAL,
Minimum_investment REAL,
Fund_Manager VARCHAR(100),
AUM REAL,
Category VARCHAR(50),
Risk VARCHAR(100)
);

SELECT * FROM MUTUAL_FUNDS;

-- FUND NAME WITH HIGHEST RETURNS

SELECT
	FUND_NAME,
	ONE_MONTH_RETURN
FROM
	MUTUAL_FUNDS
ORDER BY
	ONE_MONTH_RETURN DESC
LIMIT
	5;

-- Fund names where morning star rating== value research rating ( one_year_return)

SELECT
	FUND_NAME,
	ONE_YEAR_RETURN,
	MORNING_STAR_RATING,
	VALUE_RESEARCH_RATING
FROM
	MUTUAL_FUNDS
WHERE
	MORNING_STAR_RATING = VALUE_RESEARCH_RATING
	AND MORNING_STAR_RATING = 5
ORDER BY
	ONE_YEAR_RETURN DESC
limit 5;

-- Fund names where morning star rating== value research rating ( three_year_return)

SELECT
	FUND_NAME,
	THREE_YEAR_RETURN,
	MORNING_STAR_RATING,
	VALUE_RESEARCH_RATING
FROM
	MUTUAL_FUNDS
WHERE
	MORNING_STAR_RATING = VALUE_RESEARCH_RATING
	AND MORNING_STAR_RATING = 5
ORDER BY
	THREE_YEAR_RETURN DESC
limit 5;

-- TOP PERFORMING FUND MANAGERS IN 1 MONTH RETURN

SELECT
	FUND_NAME,
	FUND_MANAGER,
	ONE_MONTH_RETURN
FROM
	MUTUAL_FUNDS
ORDER BY
	ONE_MONTH_RETURN DESC;

-- IN 1 YEAR 

SELECT
	FUND_NAME,
	FUND_MANAGER,
	ONE_YEAR_RETURN
FROM
	MUTUAL_FUNDS
ORDER BY
	ONE_YEAR_RETURN DESC
LIMIT 5;

-- IN 3 YEAR

SELECT
	FUND_NAME,
	FUND_MANAGER,
	THREE_YEAR_RETURN
FROM
	MUTUAL_FUNDS
ORDER BY
	THREE_YEAR_RETURN DESC
LIMIT 5;

-- FUND NAME , RETURNS , WITH RISK= VERY HIGH (1 month)

SELECT
	FUND_NAME,
	ONE_MONTH_RETURN,
	RISK
FROM
	MUTUAL_FUNDS
WHERE
	RISK='Very High'
ORDER BY
	ONE_MONTH_RETURN DESC
limit 5;

--FUND NAME , RETURNS , WITH RISK= VERY HIGH (1 year)

SELECT
	FUND_NAME,
	ONE_YEAR_RETURN,
	RISK
FROM
	MUTUAL_FUNDS
WHERE
	RISK = 'Very High'
ORDER BY
	ONE_YEAR_RETURN DESC
LIMIT
	5;

--FUND NAME , RETURNS , WITH RISK= moderately high  (1 year)

SELECT
	FUND_NAME,
	ONE_YEAR_RETURN,
	RISK
FROM
	MUTUAL_FUNDS
WHERE
	RISK = 'Moderately High'
ORDER BY
	ONE_YEAR_RETURN desc
LIMIT
	5;

--FUND NAME , RETURNS , WITH RISK= Low  (1 year)

SELECT
	FUND_NAME,
	ONE_YEAR_RETURN,
	RISK
FROM
	MUTUAL_FUNDS
WHERE
	RISK = 'Low'
ORDER BY
	ONE_YEAR_RETURN desc
LIMIT
	5;

-- for long term 3 years where risk= very high

SELECT
	FUND_NAME,
	THREE_YEAR_RETURN,
	RISK
FROM
	MUTUAL_FUNDS
WHERE
	RISK = 'Very High'
ORDER BY
	THREE_YEAR_RETURN DESC
LIMIT
	5;

-- with risk= moderately high 

SELECT
	FUND_NAME,
	THREE_YEAR_RETURN,
	RISK
FROM
	MUTUAL_FUNDS
WHERE
	RISK = 'Moderately High'
ORDER BY
	THREE_YEAR_RETURN DESC
LIMIT
	5;

-- with risk= low

SELECT
	FUND_NAME,
	THREE_YEAR_RETURN,
	RISK
FROM
	MUTUAL_FUNDS
WHERE
	RISK = 'Low'
ORDER BY
	THREE_YEAR_RETURN DESC
LIMIT
	5;

-- Comparing over the category for 1 year return ( category= equity)

SELECT DISTINCT
	(CATEGORY)
FROM
	MUTUAL_FUNDS;


SELECT
	FUND_NAME,
	ONE_YEAR_RETURN,
	CATEGORY
FROM
	MUTUAL_FUNDS
WHERE
	CATEGORY = 'Equity'
ORDER BY
	ONE_YEAR_RETURN DESC
LIMIT
	5;

-- Comparing over the category for 1 year return ( category= debt)

SELECT
	FUND_NAME,
	ONE_YEAR_RETURN,
	CATEGORY
FROM
	MUTUAL_FUNDS
WHERE
	CATEGORY = 'Debt'
ORDER BY
	ONE_YEAR_RETURN DESC
LIMIT
	5;

-- Comparing over the category for 1 year return ( category=Hybrid )

SELECT
	FUND_NAME,
	ONE_YEAR_RETURN,
	CATEGORY
FROM
	MUTUAL_FUNDS
WHERE
	CATEGORY = 'Hybrid'
ORDER BY
	ONE_YEAR_RETURN DESC
LIMIT
	5;

-- Comparing over the category for 1 year return ( category=others )

SELECT
	FUND_NAME,
	ONE_YEAR_RETURN,
	CATEGORY
FROM
	MUTUAL_FUNDS
WHERE
	CATEGORY = 'Other'
ORDER BY
	ONE_YEAR_RETURN DESC
LIMIT
	5;

-- Comparing over the category for 3 year return ( category= equity)

SELECT
	FUND_NAME,
	THREE_YEAR_RETURN,
	CATEGORY
FROM
	MUTUAL_FUNDS
WHERE
	CATEGORY = 'Equity'
ORDER BY
	THREE_YEAR_RETURN desc
LIMIT
	5;

-- Comparing over the category for 3 year return ( category= debt)

SELECT
	FUND_NAME,
	THREE_YEAR_RETURN,
	CATEGORY
FROM
	MUTUAL_FUNDS
WHERE
	CATEGORY = 'Debt'
ORDER BY
	THREE_YEAR_RETURN desc
LIMIT
	5;

-- Comparing over the category for 3 year return ( category= Hybrid)

SELECT
	FUND_NAME,
	THREE_YEAR_RETURN,
	CATEGORY
FROM
	MUTUAL_FUNDS
WHERE
	CATEGORY = 'Hybrid'
ORDER BY
	THREE_YEAR_RETURN desc
LIMIT
	5;	

-- Comparing over the category for 3 year return ( category= Other)

SELECT
	FUND_NAME,
	THREE_YEAR_RETURN,
	CATEGORY
FROM
	MUTUAL_FUNDS
WHERE
	CATEGORY = 'Other'
ORDER BY
	THREE_YEAR_RETURN desc
LIMIT
	5;	

-- MOST TRUSTED AMC , FUNDS IN RELATION TO AUM

SELECT
	AMC,
	FUND_NAME,
	AUM
FROM
	MUTUAL_FUNDS
ORDER BY
	AUM DESC
LIMIT
	5;

-- Most expensive and cheapest mutual funds

SELECT
	FUND_NAME,
	NAV
FROM
	MUTUAL_FUNDS
ORDER BY
	NAV DESC
LIMIT
	1;

SELECT
	FUND_NAME,
	NAV
FROM
	MUTUAL_FUNDS
ORDER BY
	NAV 
LIMIT
	1;

-- top 3 fund manager on the basis of 3 year return
SELECT
	FUND_MANAGER,
	THREE_YEAR_RETURN
FROM
	MUTUAL_FUNDS
ORDER BY
	THREE_YEAR_RETURN DESC
LIMIT
	3;

-- Most trusted AMC by AUM

SELECT
	AMC,
	AUM
FROM
	MUTUAL_FUNDS
ORDER BY
	AUM DESC
LIMIT
	5;
